version: '3'
services:
  openvpn-client:
    container_name: openvpn-client
    image: valtma/openvpn-client:dev
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /path/to/config:/config
